#!/bin/sh
# The next line is executed by /bin/sh, but not tcl \
exec tclsh "$0" ${1+"$@"}

set srcdir [file dirname [file normalize [info script]]]

puts "TkDND sources: $srcdir"

set libpath [file dirname [file normalize [info library]]]
set includepath [file dirname $libpath]/include
catch {file delete -force config.cache}

set bits --disable-64bit
catch {
  switch $::tcl_platform(machine) {
    amd64   {set bits --enable-64bit}
    default {set bits --disable-64bit}
  }
}

puts "+++ Running 'bash configure -srcdir=$srcdir\n\
      \                 --prefix=$srcdir/cmake/runtime\n\
      \                 --exec-prefix=$srcdir/cmake/runtime\n\
      \                 --with-tcl=$libpath\n\
      \                 --with-tk=$libpath\n\
      \                 --with-tclinclude=$includepath\n\
      \                 --with-tkinclude=$includepath\n\
      \                 $bits'\n\
      \            in directory [pwd]..."
catch {exec bash configure -srcdir=$srcdir --prefix=$srcdir/cmake/runtime \
            --exec-prefix=$srcdir/cmake/runtime \
            --with-tcl=$libpath --with-tk=$libpath \
            --with-tclinclude=$includepath \
            --with-tkinclude=$includepath $bits >@stdout 2>@stderr}
exit 0
